"""baseline: reflect current live schema

Revision ID: 396de40585cb
Revises: 
Create Date: 2026-07-20 13:29:44.047328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396de40585cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_events', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('health_days_day_key', 'health_days', type_='unique')
    op.drop_index('ix_health_days_day', table_name='health_days')
    op.create_index(op.f('ix_health_days_day'), 'health_days', ['day'], unique=True)
    op.alter_column('oauth_tokens', 'provider',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.drop_constraint('oauth_tokens_provider_key', 'oauth_tokens', type_='unique')
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=True)
    op.alter_column('sleep_sessions', 'stage',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_sleep_sessions_start_time'), 'sleep_sessions', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_sessions_start_time'), table_name='sleep_sessions')
    op.alter_column('sleep_sessions', 'stage',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.create_unique_constraint('oauth_tokens_provider_key', 'oauth_tokens', ['provider'])
    op.alter_column('oauth_tokens', 'refresh_token',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'access_token',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('oauth_tokens', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_health_days_day'), table_name='health_days')
    op.create_index('ix_health_days_day', 'health_days', ['day'], unique=False)
    op.create_unique_constraint('health_days_day_key', 'health_days', ['day'])
    op.alter_column('calendar_events', 'all_day',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
